version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: main
    assignees: [cicdbot]
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - go
    commit-message:
      prefix: "chore"
      include: "scope"
    groups:
      go-minor-patch:
        update-types:
          - minor
          - patch
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    target-branch: main
    assignees: [cicdbot]
    open-pull-requests-limit: 10
    labels:
      - dependencies
      - github_actions
    commit-message:
      prefix: "ci"
      include: "scope"
    groups:
      actions:
        patterns:
          - "*"
