version: "2"

run:
  timeout: 5m

linters:
  default: standard
  enable:
    - copyloopvar
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - misspell
    - unconvert
    - unparam
    - sloglint
  settings:
    sloglint:
      attr-only: true
      static-msg: true
      key-naming-case: snake

formatters:
  enable:
    - gofmt
    - goimports

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
