// Code generated by github.com/sortie-ai/sortie/internal/agent/clientprotocol/schemagen from the Agent Client Protocol schema tag schema-v1.21.0 (commit 272bf799f35a258c6a4107a0410ed361e83683d3). DO NOT EDIT.

package clientprotocol

import (
	"encoding/json"
	"fmt"
)

// agentAuthCapabilities is generated from the AgentAuthCapabilities definition of the pinned schema.
type agentAuthCapabilities struct {
	Meta   json.RawMessage     `json:"_meta,omitempty"`
	Logout *logoutCapabilities `json:"logout,omitempty"`
}

// agentCapabilities is generated from the AgentCapabilities definition of the pinned schema.
type agentCapabilities struct {
	Meta                json.RawMessage        `json:"_meta,omitempty"`
	Auth                *agentAuthCapabilities `json:"auth,omitempty"`
	LoadSession         *bool                  `json:"loadSession,omitempty"`
	MCPCapabilities     *mcpCapabilities       `json:"mcpCapabilities,omitempty"`
	PromptCapabilities  *promptCapabilities    `json:"promptCapabilities,omitempty"`
	SessionCapabilities *sessionCapabilities   `json:"sessionCapabilities,omitempty"`
}

// annotations is generated from the Annotations definition of the pinned schema.
type annotations struct {
	Meta         json.RawMessage `json:"_meta,omitempty"`
	Audience     *[]role         `json:"audience,omitempty"`
	LastModified *string         `json:"lastModified,omitempty"`
	Priority     *float64        `json:"priority,omitempty"`
}

// audioContent is generated from the AudioContent definition of the pinned schema.
type audioContent struct {
	Meta        json.RawMessage `json:"_meta,omitempty"`
	Annotations *annotations    `json:"annotations,omitempty"`
	Data        string          `json:"data"`
	MimeType    string          `json:"mimeType"`
}

// authCapabilities is generated from the AuthCapabilities definition of the pinned schema.
type authCapabilities struct {
	Meta     json.RawMessage `json:"_meta,omitempty"`
	Terminal *bool           `json:"terminal,omitempty"`
}

// authMethod is generated from the AuthMethod union of the pinned
// schema, which declares no discriminator; the marshaler writes exactly the
// member the caller set.
type authMethod struct {
	Terminal *authMethodTerminal `json:"-"`
	Agent    *authMethodAgent    `json:"-"`
}

func (v *authMethod) UnmarshalJSON(data []byte) error {
	var probe struct {
		Type *string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("AuthMethod: %w", err)
	}
	switch {
	case probe.Type != nil && *probe.Type == "terminal":
		v.Terminal = new(authMethodTerminal)
		return json.Unmarshal(data, v.Terminal)
	default:
		v.Agent = new(authMethodAgent)
		return json.Unmarshal(data, v.Agent)
	}
}

func (v authMethod) MarshalJSON() ([]byte, error) {
	switch {
	case v.Terminal != nil:
		return marshalWithDiscriminant(v.Terminal, "type", "terminal")
	case v.Agent != nil:
		return json.Marshal(v.Agent)
	default:
		return nil, fmt.Errorf("AuthMethod: no member set")
	}
}

// authMethodAgent is generated from the AuthMethodAgent definition of the pinned schema.
type authMethodAgent struct {
	Meta        json.RawMessage `json:"_meta,omitempty"`
	Description *string         `json:"description,omitempty"`
	ID          authMethodId    `json:"id"`
	Name        string          `json:"name"`
}

// authMethodId is generated from the AuthMethodId string definition of the pinned schema.
type authMethodId string

// authMethodTerminal is generated from the AuthMethodTerminal definition of the pinned schema.
type authMethodTerminal struct {
	Meta        json.RawMessage    `json:"_meta,omitempty"`
	Args        *[]string          `json:"args,omitempty"`
	Description *string            `json:"description,omitempty"`
	Env         *map[string]string `json:"env,omitempty"`
	ID          authMethodId       `json:"id"`
	Name        string             `json:"name"`
}

// availableCommand is generated from the AvailableCommand definition of the pinned schema.
type availableCommand struct {
	Meta        json.RawMessage        `json:"_meta,omitempty"`
	Description string                 `json:"description"`
	Input       *availableCommandInput `json:"input,omitempty"`
	Name        string                 `json:"name"`
}

// availableCommandInput is generated from the AvailableCommandInput union of the pinned
// schema, which declares a single member and therefore needs no
// discriminant to decode.
type availableCommandInput struct {
	Unstructured *unstructuredCommandInput `json:"-"`
}

func (v *availableCommandInput) UnmarshalJSON(data []byte) error {
	v.Unstructured = new(unstructuredCommandInput)
	return json.Unmarshal(data, v.Unstructured)
}

func (v availableCommandInput) MarshalJSON() ([]byte, error) {
	if v.Unstructured != nil {
		return json.Marshal(v.Unstructured)
	}
	return nil, fmt.Errorf("AvailableCommandInput: no member set")
}

// availableCommandsUpdate is generated from the AvailableCommandsUpdate definition of the pinned schema.
type availableCommandsUpdate struct {
	Meta              json.RawMessage    `json:"_meta,omitempty"`
	AvailableCommands []availableCommand `json:"availableCommands"`
}

// blobResourceContents is generated from the BlobResourceContents definition of the pinned schema.
type blobResourceContents struct {
	Meta     json.RawMessage `json:"_meta,omitempty"`
	Blob     string          `json:"blob"`
	MimeType *string         `json:"mimeType,omitempty"`
	URI      string          `json:"uri"`
}

// booleanConfigOptionCapabilities is generated from the BooleanConfigOptionCapabilities definition of the pinned schema.
type booleanConfigOptionCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
}

// cancelNotification is generated from the CancelNotification definition of the pinned schema.
type cancelNotification struct {
	Meta      json.RawMessage `json:"_meta,omitempty"`
	SessionID sessionId       `json:"sessionId"`
}

// clientCapabilities is generated from the ClientCapabilities definition of the pinned schema.
type clientCapabilities struct {
	Meta        json.RawMessage            `json:"_meta,omitempty"`
	Auth        *authCapabilities          `json:"auth,omitempty"`
	Elicitation *elicitationCapabilities   `json:"elicitation,omitempty"`
	Fs          *fileSystemCapabilities    `json:"fs,omitempty"`
	Session     *clientSessionCapabilities `json:"session,omitempty"`
	Terminal    *bool                      `json:"terminal,omitempty"`
}

// clientSessionCapabilities is generated from the ClientSessionCapabilities definition of the pinned schema.
type clientSessionCapabilities struct {
	Meta          json.RawMessage                   `json:"_meta,omitempty"`
	ConfigOptions *sessionConfigOptionsCapabilities `json:"configOptions,omitempty"`
}

// configOptionUpdate is generated from the ConfigOptionUpdate definition of the pinned schema.
type configOptionUpdate struct {
	Meta          json.RawMessage       `json:"_meta,omitempty"`
	ConfigOptions []sessionConfigOption `json:"configOptions"`
}

// content is generated from the Content definition of the pinned schema.
type content struct {
	Meta    json.RawMessage `json:"_meta,omitempty"`
	Content contentBlock    `json:"content"`
}

// contentBlock is generated from the ContentBlock discriminated union of
// the pinned schema; a variant published after the pin is carried in
// Remainder rather than refused.
type contentBlock struct {
	Type      string          `json:"type"`
	Remainder json.RawMessage `json:"-"`
}

func (v *contentBlock) UnmarshalJSON(data []byte) error {
	var probe struct {
		Value string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("ContentBlock: %w", err)
	}
	v.Type = probe.Value
	v.Remainder = append(json.RawMessage(nil), data...)
	return nil
}

func (v contentBlock) MarshalJSON() ([]byte, error) {
	if v.Remainder != nil {
		return v.Remainder, nil
	}
	return nil, fmt.Errorf("ContentBlock: no decoded payload to re-encode")
}

const (
	contentBlockText         = "text"
	contentBlockImage        = "image"
	contentBlockAudio        = "audio"
	contentBlockResourceLink = "resource_link"
	contentBlockResource     = "resource"
)

// contentChunk is generated from the ContentChunk definition of the pinned schema.
type contentChunk struct {
	Meta      json.RawMessage `json:"_meta,omitempty"`
	Content   contentBlock    `json:"content"`
	MessageID *messageId      `json:"messageId,omitempty"`
}

// cost is generated from the Cost definition of the pinned schema.
type cost struct {
	Meta     json.RawMessage `json:"_meta,omitempty"`
	Amount   float64         `json:"amount"`
	Currency string          `json:"currency"`
}

// currentModeUpdate is generated from the CurrentModeUpdate definition of the pinned schema.
type currentModeUpdate struct {
	Meta          json.RawMessage `json:"_meta,omitempty"`
	CurrentModeID sessionModeId   `json:"currentModeId"`
}

// diff is generated from the Diff definition of the pinned schema.
type diff struct {
	Meta    json.RawMessage `json:"_meta,omitempty"`
	NewText string          `json:"newText"`
	OldText *string         `json:"oldText,omitempty"`
	Path    string          `json:"path"`
}

// elicitationCapabilities is generated from the ElicitationCapabilities definition of the pinned schema.
type elicitationCapabilities struct {
	Meta json.RawMessage              `json:"_meta,omitempty"`
	Form *elicitationFormCapabilities `json:"form,omitempty"`
	URL  *elicitationUrlCapabilities  `json:"url,omitempty"`
}

// elicitationFormCapabilities is generated from the ElicitationFormCapabilities definition of the pinned schema.
type elicitationFormCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
}

// elicitationUrlCapabilities is generated from the ElicitationUrlCapabilities definition of the pinned schema.
type elicitationUrlCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
}

// embeddedResource is generated from the EmbeddedResource definition of the pinned schema.
type embeddedResource struct {
	Meta        json.RawMessage          `json:"_meta,omitempty"`
	Annotations *annotations             `json:"annotations,omitempty"`
	Resource    embeddedResourceResource `json:"resource"`
}

// embeddedResourceResource is generated from the EmbeddedResourceResource union of the pinned
// schema, which declares no discriminator; the marshaler writes exactly the
// member the caller set.
type embeddedResourceResource struct {
	TextResourceContents *textResourceContents `json:"-"`
	BlobResourceContents *blobResourceContents `json:"-"`
}

func (v *embeddedResourceResource) UnmarshalJSON(data []byte) error {
	var probe map[string]json.RawMessage
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("EmbeddedResourceResource: %w", err)
	}
	switch {
	case probe["text"] != nil:
		v.TextResourceContents = new(textResourceContents)
		return json.Unmarshal(data, v.TextResourceContents)
	default:
		v.BlobResourceContents = new(blobResourceContents)
		return json.Unmarshal(data, v.BlobResourceContents)
	}
}

func (v embeddedResourceResource) MarshalJSON() ([]byte, error) {
	switch {
	case v.TextResourceContents != nil:
		return json.Marshal(v.TextResourceContents)
	case v.BlobResourceContents != nil:
		return json.Marshal(v.BlobResourceContents)
	default:
		return nil, fmt.Errorf("EmbeddedResourceResource: no member set")
	}
}

// envVariable is generated from the EnvVariable definition of the pinned schema.
type envVariable struct {
	Meta  json.RawMessage `json:"_meta,omitempty"`
	Name  string          `json:"name"`
	Value string          `json:"value"`
}

// fileSystemCapabilities is generated from the FileSystemCapabilities definition of the pinned schema.
type fileSystemCapabilities struct {
	Meta          json.RawMessage `json:"_meta,omitempty"`
	ReadTextFile  *bool           `json:"readTextFile,omitempty"`
	WriteTextFile *bool           `json:"writeTextFile,omitempty"`
}

// httpHeader is generated from the HttpHeader definition of the pinned schema.
type httpHeader struct {
	Meta  json.RawMessage `json:"_meta,omitempty"`
	Name  string          `json:"name"`
	Value string          `json:"value"`
}

// imageContent is generated from the ImageContent definition of the pinned schema.
type imageContent struct {
	Meta        json.RawMessage `json:"_meta,omitempty"`
	Annotations *annotations    `json:"annotations,omitempty"`
	Data        string          `json:"data"`
	MimeType    string          `json:"mimeType"`
	URI         *string         `json:"uri,omitempty"`
}

// implementation is generated from the Implementation definition of the pinned schema.
type implementation struct {
	Meta    json.RawMessage `json:"_meta,omitempty"`
	Name    string          `json:"name"`
	Title   *string         `json:"title,omitempty"`
	Version string          `json:"version"`
}

// initializeRequest is generated from the InitializeRequest definition of the pinned schema.
type initializeRequest struct {
	Meta               json.RawMessage     `json:"_meta,omitempty"`
	ClientCapabilities *clientCapabilities `json:"clientCapabilities,omitempty"`
	ClientInfo         *implementation     `json:"clientInfo,omitempty"`
	ProtocolVersion    protocolVersion     `json:"protocolVersion"`
}

// initializeResponse is generated from the InitializeResponse definition of the pinned schema.
type initializeResponse struct {
	Meta              json.RawMessage    `json:"_meta,omitempty"`
	AgentCapabilities *agentCapabilities `json:"agentCapabilities,omitempty"`
	AgentInfo         *implementation    `json:"agentInfo,omitempty"`
	AuthMethods       *[]authMethod      `json:"authMethods,omitempty"`
	ProtocolVersion   protocolVersion    `json:"protocolVersion"`
}

// loadSessionRequest is generated from the LoadSessionRequest definition of the pinned schema.
type loadSessionRequest struct {
	Meta                  json.RawMessage `json:"_meta,omitempty"`
	AdditionalDirectories *[]string       `json:"additionalDirectories,omitempty"`
	Cwd                   string          `json:"cwd"`
	MCPServers            []mcpServer     `json:"mcpServers"`
	SessionID             sessionId       `json:"sessionId"`
}

// loadSessionResponse is generated from the LoadSessionResponse definition of the pinned schema.
type loadSessionResponse struct {
	Meta          json.RawMessage        `json:"_meta,omitempty"`
	ConfigOptions *[]sessionConfigOption `json:"configOptions,omitempty"`
	Modes         *sessionModeState      `json:"modes,omitempty"`
}

// logoutCapabilities is generated from the LogoutCapabilities definition of the pinned schema.
type logoutCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
}

// mcpCapabilities is generated from the McpCapabilities definition of the pinned schema.
type mcpCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
	HTTP *bool           `json:"http,omitempty"`
	SSE  *bool           `json:"sse,omitempty"`
}

// mcpServer is generated from the McpServer union of the pinned
// schema, which declares no discriminator; the marshaler writes exactly the
// member the caller set.
type mcpServer struct {
	HTTP  *mcpServerHttp  `json:"-"`
	SSE   *mcpServerSse   `json:"-"`
	Stdio *mcpServerStdio `json:"-"`
}

func (v *mcpServer) UnmarshalJSON(data []byte) error {
	var probe struct {
		Type *string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("McpServer: %w", err)
	}
	switch {
	case probe.Type != nil && *probe.Type == "http":
		v.HTTP = new(mcpServerHttp)
		return json.Unmarshal(data, v.HTTP)
	case probe.Type != nil && *probe.Type == "sse":
		v.SSE = new(mcpServerSse)
		return json.Unmarshal(data, v.SSE)
	default:
		v.Stdio = new(mcpServerStdio)
		return json.Unmarshal(data, v.Stdio)
	}
}

func (v mcpServer) MarshalJSON() ([]byte, error) {
	switch {
	case v.HTTP != nil:
		return marshalWithDiscriminant(v.HTTP, "type", "http")
	case v.SSE != nil:
		return marshalWithDiscriminant(v.SSE, "type", "sse")
	case v.Stdio != nil:
		return json.Marshal(v.Stdio)
	default:
		return nil, fmt.Errorf("McpServer: no member set")
	}
}

// mcpServerHttp is generated from the McpServerHttp definition of the pinned schema.
type mcpServerHttp struct {
	Meta    json.RawMessage `json:"_meta,omitempty"`
	Headers []httpHeader    `json:"headers"`
	Name    string          `json:"name"`
	URL     string          `json:"url"`
}

// mcpServerSse is generated from the McpServerSse definition of the pinned schema.
type mcpServerSse struct {
	Meta    json.RawMessage `json:"_meta,omitempty"`
	Headers []httpHeader    `json:"headers"`
	Name    string          `json:"name"`
	URL     string          `json:"url"`
}

// mcpServerStdio is generated from the McpServerStdio definition of the pinned schema.
type mcpServerStdio struct {
	Meta    json.RawMessage `json:"_meta,omitempty"`
	Args    []string        `json:"args"`
	Command string          `json:"command"`
	Env     []envVariable   `json:"env"`
	Name    string          `json:"name"`
}

// messageId is generated from the MessageId string definition of the pinned schema.
type messageId string

// newSessionRequest is generated from the NewSessionRequest definition of the pinned schema.
type newSessionRequest struct {
	Meta                  json.RawMessage `json:"_meta,omitempty"`
	AdditionalDirectories *[]string       `json:"additionalDirectories,omitempty"`
	Cwd                   string          `json:"cwd"`
	MCPServers            []mcpServer     `json:"mcpServers"`
}

// newSessionResponse is generated from the NewSessionResponse definition of the pinned schema.
type newSessionResponse struct {
	Meta          json.RawMessage        `json:"_meta,omitempty"`
	ConfigOptions *[]sessionConfigOption `json:"configOptions,omitempty"`
	Modes         *sessionModeState      `json:"modes,omitempty"`
	SessionID     sessionId              `json:"sessionId"`
}

// permissionOption is generated from the PermissionOption definition of the pinned schema.
type permissionOption struct {
	Meta     json.RawMessage      `json:"_meta,omitempty"`
	Kind     permissionOptionKind `json:"kind"`
	Name     string               `json:"name"`
	OptionID permissionOptionId   `json:"optionId"`
}

// permissionOptionId is generated from the PermissionOptionId string definition of the pinned schema.
type permissionOptionId string

// permissionOptionKind is generated from the PermissionOptionKind enumeration of the pinned schema.
type permissionOptionKind string

const (
	permissionOptionKindAllowOnce    permissionOptionKind = "allow_once"
	permissionOptionKindAllowAlways  permissionOptionKind = "allow_always"
	permissionOptionKindRejectOnce   permissionOptionKind = "reject_once"
	permissionOptionKindRejectAlways permissionOptionKind = "reject_always"
)

// plan is generated from the Plan definition of the pinned schema.
type plan struct {
	Meta    json.RawMessage `json:"_meta,omitempty"`
	Entries []planEntry     `json:"entries"`
}

// planEntry is generated from the PlanEntry definition of the pinned schema.
type planEntry struct {
	Meta     json.RawMessage   `json:"_meta,omitempty"`
	Content  string            `json:"content"`
	Priority planEntryPriority `json:"priority"`
	Status   planEntryStatus   `json:"status"`
}

// planEntryPriority is generated from the PlanEntryPriority enumeration of the pinned schema.
type planEntryPriority string

const (
	planEntryPriorityHigh   planEntryPriority = "high"
	planEntryPriorityMedium planEntryPriority = "medium"
	planEntryPriorityLow    planEntryPriority = "low"
)

// planEntryStatus is generated from the PlanEntryStatus enumeration of the pinned schema.
type planEntryStatus string

const (
	planEntryStatusPending    planEntryStatus = "pending"
	planEntryStatusInProgress planEntryStatus = "in_progress"
	planEntryStatusCompleted  planEntryStatus = "completed"
)

// promptCapabilities is generated from the PromptCapabilities definition of the pinned schema.
type promptCapabilities struct {
	Meta            json.RawMessage `json:"_meta,omitempty"`
	Audio           *bool           `json:"audio,omitempty"`
	EmbeddedContext *bool           `json:"embeddedContext,omitempty"`
	Image           *bool           `json:"image,omitempty"`
}

// promptRequest is generated from the PromptRequest definition of the pinned schema.
type promptRequest struct {
	Meta      json.RawMessage `json:"_meta,omitempty"`
	Prompt    []contentBlock  `json:"prompt"`
	SessionID sessionId       `json:"sessionId"`
}

// promptResponse is generated from the PromptResponse definition of the pinned schema.
type promptResponse struct {
	Meta       json.RawMessage `json:"_meta,omitempty"`
	StopReason stopReason      `json:"stopReason"`
}

// protocolVersion is generated from the ProtocolVersion integer definition of the pinned schema.
type protocolVersion int64

// requestPermissionOutcome is generated from the RequestPermissionOutcome discriminated union of
// the pinned schema; a variant published after the pin is carried in
// Remainder rather than refused.
type requestPermissionOutcome struct {
	Outcome   string          `json:"outcome"`
	Remainder json.RawMessage `json:"-"`
}

func (v *requestPermissionOutcome) UnmarshalJSON(data []byte) error {
	var probe struct {
		Value string `json:"outcome"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("RequestPermissionOutcome: %w", err)
	}
	v.Outcome = probe.Value
	v.Remainder = append(json.RawMessage(nil), data...)
	return nil
}

func (v requestPermissionOutcome) MarshalJSON() ([]byte, error) {
	if v.Remainder != nil {
		return v.Remainder, nil
	}
	return nil, fmt.Errorf("RequestPermissionOutcome: no decoded payload to re-encode")
}

const (
	requestPermissionOutcomeCancelled = "cancelled"
	requestPermissionOutcomeSelected  = "selected"
)

// requestPermissionRequest is generated from the RequestPermissionRequest definition of the pinned schema.
type requestPermissionRequest struct {
	Meta      json.RawMessage    `json:"_meta,omitempty"`
	Options   []permissionOption `json:"options"`
	SessionID sessionId          `json:"sessionId"`
	ToolCall  toolCallUpdate     `json:"toolCall"`
}

// requestPermissionResponse is generated from the RequestPermissionResponse definition of the pinned schema.
type requestPermissionResponse struct {
	Meta    json.RawMessage          `json:"_meta,omitempty"`
	Outcome requestPermissionOutcome `json:"outcome"`
}

// resourceLink is generated from the ResourceLink definition of the pinned schema.
type resourceLink struct {
	Meta        json.RawMessage `json:"_meta,omitempty"`
	Annotations *annotations    `json:"annotations,omitempty"`
	Description *string         `json:"description,omitempty"`
	MimeType    *string         `json:"mimeType,omitempty"`
	Name        string          `json:"name"`
	Size        *int64          `json:"size,omitempty"`
	Title       *string         `json:"title,omitempty"`
	URI         string          `json:"uri"`
}

// resumeSessionRequest is generated from the ResumeSessionRequest definition of the pinned schema.
type resumeSessionRequest struct {
	Meta                  json.RawMessage `json:"_meta,omitempty"`
	AdditionalDirectories *[]string       `json:"additionalDirectories,omitempty"`
	Cwd                   string          `json:"cwd"`
	MCPServers            *[]mcpServer    `json:"mcpServers,omitempty"`
	SessionID             sessionId       `json:"sessionId"`
}

// resumeSessionResponse is generated from the ResumeSessionResponse definition of the pinned schema.
type resumeSessionResponse struct {
	Meta          json.RawMessage        `json:"_meta,omitempty"`
	ConfigOptions *[]sessionConfigOption `json:"configOptions,omitempty"`
	Modes         *sessionModeState      `json:"modes,omitempty"`
}

// role is generated from the Role enumeration of the pinned schema.
type role string

const (
	roleAssistant role = "assistant"
	roleUser      role = "user"
)

// selectedPermissionOutcome is generated from the SelectedPermissionOutcome definition of the pinned schema.
type selectedPermissionOutcome struct {
	Meta     json.RawMessage    `json:"_meta,omitempty"`
	OptionID permissionOptionId `json:"optionId"`
}

// sessionAdditionalDirectoriesCapabilities is generated from the SessionAdditionalDirectoriesCapabilities definition of the pinned schema.
type sessionAdditionalDirectoriesCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
}

// sessionCapabilities is generated from the SessionCapabilities definition of the pinned schema.
type sessionCapabilities struct {
	Meta                  json.RawMessage                           `json:"_meta,omitempty"`
	AdditionalDirectories *sessionAdditionalDirectoriesCapabilities `json:"additionalDirectories,omitempty"`
	Close                 *sessionCloseCapabilities                 `json:"close,omitempty"`
	Delete                *sessionDeleteCapabilities                `json:"delete,omitempty"`
	List                  *sessionListCapabilities                  `json:"list,omitempty"`
	Resume                *sessionResumeCapabilities                `json:"resume,omitempty"`
}

// sessionCloseCapabilities is generated from the SessionCloseCapabilities definition of the pinned schema.
type sessionCloseCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
}

// sessionConfigBoolean is generated from the SessionConfigBoolean definition of the pinned schema.
type sessionConfigBoolean struct {
	CurrentValue bool `json:"currentValue"`
}

// sessionConfigGroupId is generated from the SessionConfigGroupId string definition of the pinned schema.
type sessionConfigGroupId string

// sessionConfigId is generated from the SessionConfigId string definition of the pinned schema.
type sessionConfigId string

// sessionConfigOption is generated from the SessionConfigOption discriminated union of
// the pinned schema; a variant published after the pin is carried in
// Remainder rather than refused.
type sessionConfigOption struct {
	Type      string          `json:"type"`
	Remainder json.RawMessage `json:"-"`
}

func (v *sessionConfigOption) UnmarshalJSON(data []byte) error {
	var probe struct {
		Value string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("SessionConfigOption: %w", err)
	}
	v.Type = probe.Value
	v.Remainder = append(json.RawMessage(nil), data...)
	return nil
}

func (v sessionConfigOption) MarshalJSON() ([]byte, error) {
	if v.Remainder != nil {
		return v.Remainder, nil
	}
	return nil, fmt.Errorf("SessionConfigOption: no decoded payload to re-encode")
}

const (
	sessionConfigOptionSelect  = "select"
	sessionConfigOptionBoolean = "boolean"
)

// sessionConfigOptionCategory is generated from the SessionConfigOptionCategory open-ended string enumeration of
// the pinned schema; the artifact reserves an uncategorized value that
// this underlying-string type accepts without a matching constant.
type sessionConfigOptionCategory string

const (
	sessionConfigOptionCategoryMode         sessionConfigOptionCategory = "mode"
	sessionConfigOptionCategoryModel        sessionConfigOptionCategory = "model"
	sessionConfigOptionCategoryModelConfig  sessionConfigOptionCategory = "model_config"
	sessionConfigOptionCategoryThoughtLevel sessionConfigOptionCategory = "thought_level"
)

// sessionConfigOptionsCapabilities is generated from the SessionConfigOptionsCapabilities definition of the pinned schema.
type sessionConfigOptionsCapabilities struct {
	Meta    json.RawMessage                  `json:"_meta,omitempty"`
	Boolean *booleanConfigOptionCapabilities `json:"boolean,omitempty"`
}

// sessionConfigSelect is generated from the SessionConfigSelect definition of the pinned schema.
type sessionConfigSelect struct {
	CurrentValue sessionConfigValueId       `json:"currentValue"`
	Options      sessionConfigSelectOptions `json:"options"`
}

// sessionConfigSelectGroup is generated from the SessionConfigSelectGroup definition of the pinned schema.
type sessionConfigSelectGroup struct {
	Meta    json.RawMessage             `json:"_meta,omitempty"`
	Group   sessionConfigGroupId        `json:"group"`
	Name    string                      `json:"name"`
	Options []sessionConfigSelectOption `json:"options"`
}

// sessionConfigSelectOption is generated from the SessionConfigSelectOption definition of the pinned schema.
type sessionConfigSelectOption struct {
	Meta        json.RawMessage      `json:"_meta,omitempty"`
	Description *string              `json:"description,omitempty"`
	Name        string               `json:"name"`
	Value       sessionConfigValueId `json:"value"`
}

// sessionConfigSelectOptions is generated from the SessionConfigSelectOptions union of the pinned
// schema, whose members are all arrays and which declares no discriminator;
// the marshaler writes exactly the member the caller set.
type sessionConfigSelectOptions struct {
	Ungrouped []sessionConfigSelectOption `json:"-"`
	Grouped   []sessionConfigSelectGroup  `json:"-"`
}

func (v *sessionConfigSelectOptions) UnmarshalJSON(data []byte) error {
	var elems []json.RawMessage
	if err := json.Unmarshal(data, &elems); err != nil {
		return fmt.Errorf("SessionConfigSelectOptions: %w", err)
	}
	var probe map[string]json.RawMessage
	if len(elems) > 0 {
		_ = json.Unmarshal(elems[0], &probe)
	}
	switch {
	case probe["value"] != nil:
		return json.Unmarshal(data, &v.Ungrouped)
	default:
		return json.Unmarshal(data, &v.Grouped)
	}
}

func (v sessionConfigSelectOptions) MarshalJSON() ([]byte, error) {
	switch {
	case v.Ungrouped != nil:
		return json.Marshal(v.Ungrouped)
	case v.Grouped != nil:
		return json.Marshal(v.Grouped)
	default:
		return nil, fmt.Errorf("SessionConfigSelectOptions: no member is set")
	}
}

// sessionConfigValueId is generated from the SessionConfigValueId string definition of the pinned schema.
type sessionConfigValueId string

// sessionDeleteCapabilities is generated from the SessionDeleteCapabilities definition of the pinned schema.
type sessionDeleteCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
}

// sessionId is generated from the SessionId string definition of the pinned schema.
type sessionId string

// sessionInfoUpdate is generated from the SessionInfoUpdate definition of the pinned schema.
type sessionInfoUpdate struct {
	Meta      json.RawMessage `json:"_meta,omitempty"`
	Title     *string         `json:"title,omitempty"`
	UpdatedAt *string         `json:"updatedAt,omitempty"`
}

// sessionListCapabilities is generated from the SessionListCapabilities definition of the pinned schema.
type sessionListCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
}

// sessionMode is generated from the SessionMode definition of the pinned schema.
type sessionMode struct {
	Meta        json.RawMessage `json:"_meta,omitempty"`
	Description *string         `json:"description,omitempty"`
	ID          sessionModeId   `json:"id"`
	Name        string          `json:"name"`
}

// sessionModeId is generated from the SessionModeId string definition of the pinned schema.
type sessionModeId string

// sessionModeState is generated from the SessionModeState definition of the pinned schema.
type sessionModeState struct {
	Meta           json.RawMessage `json:"_meta,omitempty"`
	AvailableModes []sessionMode   `json:"availableModes"`
	CurrentModeID  sessionModeId   `json:"currentModeId"`
}

// sessionNotification is generated from the SessionNotification definition of the pinned schema.
type sessionNotification struct {
	Meta      json.RawMessage `json:"_meta,omitempty"`
	SessionID sessionId       `json:"sessionId"`
	Update    sessionUpdate   `json:"update"`
}

// sessionResumeCapabilities is generated from the SessionResumeCapabilities definition of the pinned schema.
type sessionResumeCapabilities struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
}

// sessionUpdate is generated from the SessionUpdate discriminated union of
// the pinned schema; a variant published after the pin is carried in
// Remainder rather than refused.
type sessionUpdate struct {
	SessionUpdate string          `json:"sessionUpdate"`
	Remainder     json.RawMessage `json:"-"`
}

func (v *sessionUpdate) UnmarshalJSON(data []byte) error {
	var probe struct {
		Value string `json:"sessionUpdate"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("SessionUpdate: %w", err)
	}
	v.SessionUpdate = probe.Value
	v.Remainder = append(json.RawMessage(nil), data...)
	return nil
}

func (v sessionUpdate) MarshalJSON() ([]byte, error) {
	if v.Remainder != nil {
		return v.Remainder, nil
	}
	return nil, fmt.Errorf("SessionUpdate: no decoded payload to re-encode")
}

const (
	sessionUpdateUserMessageChunk        = "user_message_chunk"
	sessionUpdateAgentMessageChunk       = "agent_message_chunk"
	sessionUpdateAgentThoughtChunk       = "agent_thought_chunk"
	sessionUpdateToolCall                = "tool_call"
	sessionUpdateToolCallUpdate          = "tool_call_update"
	sessionUpdatePlan                    = "plan"
	sessionUpdateAvailableCommandsUpdate = "available_commands_update"
	sessionUpdateCurrentModeUpdate       = "current_mode_update"
	sessionUpdateConfigOptionUpdate      = "config_option_update"
	sessionUpdateSessionInfoUpdate       = "session_info_update"
	sessionUpdateUsageUpdate             = "usage_update"
)

// stopReason is generated from the StopReason enumeration of the pinned schema.
type stopReason string

const (
	stopReasonEndTurn         stopReason = "end_turn"
	stopReasonMaxTokens       stopReason = "max_tokens"
	stopReasonMaxTurnRequests stopReason = "max_turn_requests"
	stopReasonRefusal         stopReason = "refusal"
	stopReasonCancelled       stopReason = "cancelled"
)

// terminal is generated from the Terminal definition of the pinned schema.
type terminal struct {
	Meta       json.RawMessage `json:"_meta,omitempty"`
	TerminalID terminalId      `json:"terminalId"`
}

// terminalId is generated from the TerminalId string definition of the pinned schema.
type terminalId string

// textContent is generated from the TextContent definition of the pinned schema.
type textContent struct {
	Meta        json.RawMessage `json:"_meta,omitempty"`
	Annotations *annotations    `json:"annotations,omitempty"`
	Text        string          `json:"text"`
}

// textResourceContents is generated from the TextResourceContents definition of the pinned schema.
type textResourceContents struct {
	Meta     json.RawMessage `json:"_meta,omitempty"`
	MimeType *string         `json:"mimeType,omitempty"`
	Text     string          `json:"text"`
	URI      string          `json:"uri"`
}

// toolCall is generated from the ToolCall definition of the pinned schema.
type toolCall struct {
	Meta       json.RawMessage     `json:"_meta,omitempty"`
	Content    *[]toolCallContent  `json:"content,omitempty"`
	Kind       *toolKind           `json:"kind,omitempty"`
	Locations  *[]toolCallLocation `json:"locations,omitempty"`
	RawInput   *json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput  *json.RawMessage    `json:"rawOutput,omitempty"`
	Status     *toolCallStatus     `json:"status,omitempty"`
	Title      string              `json:"title"`
	ToolCallID toolCallId          `json:"toolCallId"`
}

// toolCallContent is generated from the ToolCallContent discriminated union of
// the pinned schema; a variant published after the pin is carried in
// Remainder rather than refused.
type toolCallContent struct {
	Type      string          `json:"type"`
	Remainder json.RawMessage `json:"-"`
}

func (v *toolCallContent) UnmarshalJSON(data []byte) error {
	var probe struct {
		Value string `json:"type"`
	}
	if err := json.Unmarshal(data, &probe); err != nil {
		return fmt.Errorf("ToolCallContent: %w", err)
	}
	v.Type = probe.Value
	v.Remainder = append(json.RawMessage(nil), data...)
	return nil
}

func (v toolCallContent) MarshalJSON() ([]byte, error) {
	if v.Remainder != nil {
		return v.Remainder, nil
	}
	return nil, fmt.Errorf("ToolCallContent: no decoded payload to re-encode")
}

const (
	toolCallContentContent  = "content"
	toolCallContentDiff     = "diff"
	toolCallContentTerminal = "terminal"
)

// toolCallId is generated from the ToolCallId string definition of the pinned schema.
type toolCallId string

// toolCallLocation is generated from the ToolCallLocation definition of the pinned schema.
type toolCallLocation struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
	Line *int64          `json:"line,omitempty"`
	Path string          `json:"path"`
}

// toolCallStatus is generated from the ToolCallStatus enumeration of the pinned schema.
type toolCallStatus string

const (
	toolCallStatusPending    toolCallStatus = "pending"
	toolCallStatusInProgress toolCallStatus = "in_progress"
	toolCallStatusCompleted  toolCallStatus = "completed"
	toolCallStatusFailed     toolCallStatus = "failed"
)

// toolCallUpdate is generated from the ToolCallUpdate definition of the pinned schema.
type toolCallUpdate struct {
	Meta       json.RawMessage     `json:"_meta,omitempty"`
	Content    *[]toolCallContent  `json:"content,omitempty"`
	Kind       *toolKind           `json:"kind,omitempty"`
	Locations  *[]toolCallLocation `json:"locations,omitempty"`
	RawInput   *json.RawMessage    `json:"rawInput,omitempty"`
	RawOutput  *json.RawMessage    `json:"rawOutput,omitempty"`
	Status     *toolCallStatus     `json:"status,omitempty"`
	Title      *string             `json:"title,omitempty"`
	ToolCallID toolCallId          `json:"toolCallId"`
}

// toolKind is generated from the ToolKind enumeration of the pinned schema.
type toolKind string

const (
	toolKindRead       toolKind = "read"
	toolKindEdit       toolKind = "edit"
	toolKindDelete     toolKind = "delete"
	toolKindMove       toolKind = "move"
	toolKindSearch     toolKind = "search"
	toolKindExecute    toolKind = "execute"
	toolKindThink      toolKind = "think"
	toolKindFetch      toolKind = "fetch"
	toolKindSwitchMode toolKind = "switch_mode"
	toolKindOther      toolKind = "other"
)

// unstructuredCommandInput is generated from the UnstructuredCommandInput definition of the pinned schema.
type unstructuredCommandInput struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
	Hint string          `json:"hint"`
}

// usageUpdate is generated from the UsageUpdate definition of the pinned schema.
type usageUpdate struct {
	Meta json.RawMessage `json:"_meta,omitempty"`
	Cost *cost           `json:"cost,omitempty"`
	Size int64           `json:"size"`
	Used int64           `json:"used"`
}

// marshalWithDiscriminant marshals v and injects the key/value pair that
// a non-discriminated union member's wrapper schema adds beside it.
func marshalWithDiscriminant(v interface{}, key, value string) ([]byte, error) {
	body, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	var fields map[string]json.RawMessage
	if err := json.Unmarshal(body, &fields); err != nil {
		return nil, err
	}
	encodedValue, err := json.Marshal(value)
	if err != nil {
		return nil, err
	}
	fields[key] = encodedValue
	return json.Marshal(fields)
}

// wireTypeByDefinition maps each pinned schema definition this generator
// reached to the Go type emitted for it.
var wireTypeByDefinition = map[string]string{
	"AgentAuthCapabilities":                    "agentAuthCapabilities",
	"AgentCapabilities":                        "agentCapabilities",
	"Annotations":                              "annotations",
	"AudioContent":                             "audioContent",
	"AuthCapabilities":                         "authCapabilities",
	"AuthMethod":                               "authMethod",
	"AuthMethodAgent":                          "authMethodAgent",
	"AuthMethodId":                             "authMethodId",
	"AuthMethodTerminal":                       "authMethodTerminal",
	"AvailableCommand":                         "availableCommand",
	"AvailableCommandInput":                    "availableCommandInput",
	"AvailableCommandsUpdate":                  "availableCommandsUpdate",
	"BlobResourceContents":                     "blobResourceContents",
	"BooleanConfigOptionCapabilities":          "booleanConfigOptionCapabilities",
	"CancelNotification":                       "cancelNotification",
	"ClientCapabilities":                       "clientCapabilities",
	"ClientSessionCapabilities":                "clientSessionCapabilities",
	"ConfigOptionUpdate":                       "configOptionUpdate",
	"Content":                                  "content",
	"ContentBlock":                             "contentBlock",
	"ContentChunk":                             "contentChunk",
	"Cost":                                     "cost",
	"CurrentModeUpdate":                        "currentModeUpdate",
	"Diff":                                     "diff",
	"ElicitationCapabilities":                  "elicitationCapabilities",
	"ElicitationFormCapabilities":              "elicitationFormCapabilities",
	"ElicitationUrlCapabilities":               "elicitationUrlCapabilities",
	"EmbeddedResource":                         "embeddedResource",
	"EmbeddedResourceResource":                 "embeddedResourceResource",
	"EnvVariable":                              "envVariable",
	"FileSystemCapabilities":                   "fileSystemCapabilities",
	"HttpHeader":                               "httpHeader",
	"ImageContent":                             "imageContent",
	"Implementation":                           "implementation",
	"InitializeRequest":                        "initializeRequest",
	"InitializeResponse":                       "initializeResponse",
	"LoadSessionRequest":                       "loadSessionRequest",
	"LoadSessionResponse":                      "loadSessionResponse",
	"LogoutCapabilities":                       "logoutCapabilities",
	"McpCapabilities":                          "mcpCapabilities",
	"McpServer":                                "mcpServer",
	"McpServerHttp":                            "mcpServerHttp",
	"McpServerSse":                             "mcpServerSse",
	"McpServerStdio":                           "mcpServerStdio",
	"MessageId":                                "messageId",
	"NewSessionRequest":                        "newSessionRequest",
	"NewSessionResponse":                       "newSessionResponse",
	"PermissionOption":                         "permissionOption",
	"PermissionOptionId":                       "permissionOptionId",
	"PermissionOptionKind":                     "permissionOptionKind",
	"Plan":                                     "plan",
	"PlanEntry":                                "planEntry",
	"PlanEntryPriority":                        "planEntryPriority",
	"PlanEntryStatus":                          "planEntryStatus",
	"PromptCapabilities":                       "promptCapabilities",
	"PromptRequest":                            "promptRequest",
	"PromptResponse":                           "promptResponse",
	"ProtocolVersion":                          "protocolVersion",
	"RequestPermissionOutcome":                 "requestPermissionOutcome",
	"RequestPermissionRequest":                 "requestPermissionRequest",
	"RequestPermissionResponse":                "requestPermissionResponse",
	"ResourceLink":                             "resourceLink",
	"ResumeSessionRequest":                     "resumeSessionRequest",
	"ResumeSessionResponse":                    "resumeSessionResponse",
	"Role":                                     "role",
	"SelectedPermissionOutcome":                "selectedPermissionOutcome",
	"SessionAdditionalDirectoriesCapabilities": "sessionAdditionalDirectoriesCapabilities",
	"SessionCapabilities":                      "sessionCapabilities",
	"SessionCloseCapabilities":                 "sessionCloseCapabilities",
	"SessionConfigBoolean":                     "sessionConfigBoolean",
	"SessionConfigGroupId":                     "sessionConfigGroupId",
	"SessionConfigId":                          "sessionConfigId",
	"SessionConfigOption":                      "sessionConfigOption",
	"SessionConfigOptionCategory":              "sessionConfigOptionCategory",
	"SessionConfigOptionsCapabilities":         "sessionConfigOptionsCapabilities",
	"SessionConfigSelect":                      "sessionConfigSelect",
	"SessionConfigSelectGroup":                 "sessionConfigSelectGroup",
	"SessionConfigSelectOption":                "sessionConfigSelectOption",
	"SessionConfigSelectOptions":               "sessionConfigSelectOptions",
	"SessionConfigValueId":                     "sessionConfigValueId",
	"SessionDeleteCapabilities":                "sessionDeleteCapabilities",
	"SessionId":                                "sessionId",
	"SessionInfoUpdate":                        "sessionInfoUpdate",
	"SessionListCapabilities":                  "sessionListCapabilities",
	"SessionMode":                              "sessionMode",
	"SessionModeId":                            "sessionModeId",
	"SessionModeState":                         "sessionModeState",
	"SessionNotification":                      "sessionNotification",
	"SessionResumeCapabilities":                "sessionResumeCapabilities",
	"SessionUpdate":                            "sessionUpdate",
	"StopReason":                               "stopReason",
	"Terminal":                                 "terminal",
	"TerminalId":                               "terminalId",
	"TextContent":                              "textContent",
	"TextResourceContents":                     "textResourceContents",
	"ToolCall":                                 "toolCall",
	"ToolCallContent":                          "toolCallContent",
	"ToolCallId":                               "toolCallId",
	"ToolCallLocation":                         "toolCallLocation",
	"ToolCallStatus":                           "toolCallStatus",
	"ToolCallUpdate":                           "toolCallUpdate",
	"ToolKind":                                 "toolKind",
	"UnstructuredCommandInput":                 "unstructuredCommandInput",
	"UsageUpdate":                              "usageUpdate",
}

// Method-name constants generated from the pinned method index (meta.json).
const (
	methodAuthenticate             = "authenticate"
	methodCancelRequest            = "$/cancel_request"
	methodElicitationComplete      = "elicitation/complete"
	methodElicitationCreate        = "elicitation/create"
	methodFsReadTextFile           = "fs/read_text_file"
	methodFsWriteTextFile          = "fs/write_text_file"
	methodInitialize               = "initialize"
	methodLogout                   = "logout"
	methodSessionCancel            = "session/cancel"
	methodSessionClose             = "session/close"
	methodSessionDelete            = "session/delete"
	methodSessionList              = "session/list"
	methodSessionLoad              = "session/load"
	methodSessionNew               = "session/new"
	methodSessionPrompt            = "session/prompt"
	methodSessionRequestPermission = "session/request_permission"
	methodSessionResume            = "session/resume"
	methodSessionSetConfigOption   = "session/set_config_option"
	methodSessionSetMode           = "session/set_mode"
	methodSessionUpdate            = "session/update"
	methodTerminalCreate           = "terminal/create"
	methodTerminalKill             = "terminal/kill"
	methodTerminalOutput           = "terminal/output"
	methodTerminalRelease          = "terminal/release"
	methodTerminalWaitForExit      = "terminal/wait_for_exit"
)
